name: ci-cd

on:
  push:
    paths:
        - src/**
    branches: 
        - main

jobs:
  ci:
    runs-on: ubuntu-latest #arc-runner-set
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Shorten action commit ID
        shell: bash
        run: |
            echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: taiwrash/python-api:${{ env.COMMIT_ID }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
    outputs:
      commit_id: ${{ env.COMMIT_ID  }}

  cd:
    needs: ci
    runs-on: arc-runner-set
    steps:
        - name: Checkout code
          uses: actions/checkout@v6



        - name: Install with Argo CD 
          shell: bash
    
          run: |
            curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
            sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
            rm argocd-linux-amd64


        - name: Login to Argo CD 
          shell: bash
          run: |
            argocd login argocd-server.argocd --password ${{ secrets.ARGOCD_PASSWORD }} --username admin --grpc-web --insecure 
            argocd app set python-app --helm-set image.tag=${{ needs.ci.outputs.commit_id }}

        - name: Sync to Argo CD 
          shell: bash
          run: |
              argocd app sync python-api