name: ci-cd

on:
  push:
    paths:
        - src/**
    branches: 
        - main

jobs:
  ci:
    runs-on: ubuntu-latest #arc-runner-set
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Shorten action commit ID
        shell: bash
        run: |
            echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: taiwrash/python-api:${{ env.COMMIT_ID }}
    outputs:
      commit_id: ${{ env.COMMIT_ID  }}

  cd:
    needs: ci
    runs-on: arc-runner-set
    steps:
        - name: Checkout code
          uses: actions/checkout@v6

        - name: Modify values file
          shell: bash
          run: |
            echo ${{needs.ci.outputs.commit_id}}
            sudo apt install python3
            sudo apt install python3-pip
            pip install yq
            yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/python-api/values.yaml


        - name: Commit changes
          uses: EndBug/add-and-commit@v9
          with:
            message: 'Updates values.yaml with commit ${{needs.ci.outputs.commit_id}}'

        - name: Install with Argo CD 
          shell: bash
          run: |
            curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
            sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
            rm argocd-linux-amd64


        - name: Login to Argo CD 
          shell: bash
          run: |
            argocd login argocd-server.argocd --password ${{ secrets.ARGOCD_PASSWORD }} --username admin --grpc-web --insecure 

        - name: Sync to Argo CD 
          shell: bash
          run: |
              argocd app sync python-api